### ISSUE TITLE
tooltip in ListView item crash

### ISSUE THREAD

**Issue by sgehrman** [stargazing-dino/just_the_tooltip#31]
I haven't investigated this yet.  But I added a tooltip on some listview items and I'm getting this:

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: RenderFlex children have non-zero flex but incoming width constraints are unbounded.
When a row is in a parent that does not provide a finite width constraint, for example if it is in a horizontal scrollable, it will try to shrink-wrap its children along the horizontal axis. Setting a flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining space in the horizontal direction.
These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child cannot simultaneously expand to fit its parent.
Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible children (using Flexible rather than Expanded). This will allow the flexible children to size themselves to less than the infinite remaining space they would otherwise be forced to take, and then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum constraints provided by the parent.
If this message did not help you determine the problem, consider using debugDumpRenderTree():
  https://flutter.dev/debugging/#rendering-layer
  http://api.flutter.dev/flutter/rendering/debugDumpRenderTree.html
The affected RenderFlex is:
  RenderFlex#88256 relayoutBoundary=up18(creator: Row ← Padding ← DefaultTextStyle ← Builder ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#2bfc5 ink renderer] ← NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← ⋯, parentData: offset=Offset(10.0, 10.0) (can use size), constraints: BoxConstraints(w=849.8, 0.0<=h<=Infinity), size: Size(849.8, 60.0), direction: horizontal, mainAxisAlignment: start, mainAxisSize: max, crossAxisAlignment: center, textDirection: ltr, verticalDirection: down)
The creator information is set to:
  Row ← Padding ← DefaultTextStyle ← Builder ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#2bfc5 ink renderer] ← NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← ⋯
See also: https://flutter.dev/layout/
If none of the above helps enough to fix this problem, please don't hesitate to file a bug:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
#0      RenderBox.debugCannotComputeDryLayout.<anonymous closure>
#1      RenderBox.debugCannotComputeDryLayout
#2      RenderFlex.computeDryLayout
#3      RenderBox._computeDryLayout
#4      RenderBox.getDryLayout.<anonymous closure>
#5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#6      RenderBox.getDryLayout
#7      RenderPadding.computeDryLayout
#8      RenderBox._computeDryLayout
#9      RenderBox.getDryLayout.<anonymous closure>
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#11     RenderBox.getDryLayout
#12     RenderProxyBoxMixin.computeDryLayout
#13     RenderBox._computeDryLayout
#14     RenderBox.getDryLayout.<anonymous closure>
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#16     RenderBox.getDryLayout
#17     RenderProxyBoxMixin.computeDryLayout
#18     RenderBox._computeDryLayout
#19     RenderBox.getDryLayout.<anonymous closure>
#20     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#21     RenderBox.getDryLayout
#22     RenderProxyBoxMixin.computeDryLayout
#23     RenderBox._computeDryLayout
#24     RenderBox.getDryLayout.<anonymous closure>
#25     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#26     RenderBox.getDryLayout
#27     RenderProxyBoxMixin.computeDryLayout
#28     RenderBox._computeDryLayout
#29     RenderBox.getDryLayout.<anonymous closure>
#30     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#31     RenderBox.getDryLayout
#32     RenderPadding.computeDryLayout
#33     RenderBox._computeDryLayout
#34     RenderBox.getDryLayout.<anonymous closure>
#35     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#36     RenderBox.getDryLayout
#37     RenderProxyBoxMixin.computeDryLayout
#38     RenderBox._computeDryLayout
#39     RenderBox.getDryLayout.<anonymous closure>
#40     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#41     RenderBox.getDryLayout
#42     RenderProxyBoxMixin.computeDryLayout
#43     RenderBox._computeDryLayout
#44     RenderBox.getDryLayout.<anonymous closure>
#45     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#46     RenderBox.getDryLayout
#47     RenderProxyBoxMixin.computeDryLayout
#48     RenderBox._computeDryLayout
#49     RenderBox.getDryLayout.<anonymous closure>
#50     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#51     RenderBox.getDryLayout
#52     _JustTheTooltipState._getTargetInformation
#53     _JustTheTooltipState._createEntry
#54     _JustTheTooltipState._createNewEntries
#55     _JustTheTooltipState.ensureTooltipVisible
#56     _JustTheTooltipState._showTooltip.<anonymous closure>
#57     _JustTheTooltipState._showTooltip.<anonymous closure>
#58     _rootRun (dart:async/zone.dart:1420:47)
#59     _CustomZone.run (dart:async/zone.dart:1328:19)
#60     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#61     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#62     _rootRun (dart:async/zone.dart:1428:13)
#63     _CustomZone.run (dart:async/zone.dart:1328:19)
#64     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#65     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#66     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#67     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:187:12)

**Comment by sgehrman** [comment]
I have a PageView that horizontally scrolls pages, and each page is a listView and I put a tooltip on the list view items.

**Comment by sgehrman** [comment]
I fixed it.

I had a row, and icon and a Text and I set the row to:

mainAxisSize: MainAxisSize.min,

It doesn't crash now.

**Comment by sgehrman** [comment]
I'm seeing this again in another list.  Something is not right.
